# TP1:Cadrage BI, processus métier et découverte des sources

1.1. Contexte professionnel
Une entreprise de commerce en ligne souhaite mieux comprendre son activité de vente à partir de son historique 
transactionnel. En tant que junior BI analyst, notre mission consiste à formaliser le besoin décisionnel, à identifier les 
questions métier pertinentes, à représenter le processus principal de vente et à vérifier les sources de données disponibles.

1.2. Besoin décisionnel
Le besoin décisionnel consiste à fournir à la direction une meilleure compréhension de l'activité commerciale afin de suivre
l'évolution des ventes dans le temps, d'identifier les produits les plus vendus, de comparer les ventes selon les pays et 
d'examiner les commandes et les clients identifiés ou inconnus.

Question du TP et Réponse proposée

Que devons-nous décider ou comprendre ?

Comprendre l'évolution des ventes, les produits vendus, la répartition par pays et les informations relatives aux clients.


Quelles questions peuvent être mesurées ?

Les ventes par date, les quantités par produit et par pays, ainsi que le nombre de commandes et les clients identifiés.


Quel est le processus métier observable ?

Le processus de vente de produits.


Quels champs sont nécessaires ?

InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country.


Quelle est la limite de la source ?

Certaines informations peuvent être manquantes ; le fichier ne décrit pas nécessairement toutes les étapes du processus commercial.


Comment vérifier l'inventaire ?

Comparer les colonnes réellement observées dans le fichier avec les huit colonnes attendues.

In [2]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\pc
['.anaconda', '.conda', '.condarc', '.continuum', '.dgl', '.dotnet', '.equo', '.idlerc', '.ipynb_checkpoints', '.ipython', '.javacpp', '.jupyter', '.knime', '.matplotlib', '.nuget', '.packettracer', '.spss', '.spyder-py3', '.templateengine', '.VirtualBox', '.vscode', '.vscode-shared', 'anaconda3', 'AppData', 'Application Data', 'bs.ipynb', 'Cisco Packet Tracer 9.0.0', 'Contacts', 'Cookies', 'Desktop', 'Documents', 'Downloads', 'env', 'Favorites', 'GNS3', 'import tkinter as tk.py', 'IntelGraphicsProfiles', 'Jedi', 'knime-workspace', 'KNIME_project2.knwf', 'Links', 'Local Settings', 'logs', 'Menu Démarrer', 'Mes documents', 'Microsoft', 'Modèles', 'Music', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TM.blf', 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Online Retail.xlsx', 'Pictures', 'PycharmProjects', 'Recent', 'ryu-env', 'Saved Games', 'Searches', 'SendTo', 'source', 'TD7_Data_mining_RegressionLogistique.ipynb', 'TP 1 DL ML.ipynb', 'TP 5 ML&DL.ipynb', 'TP 6 ML&DL.ipynb', 'TP1 BI  M1.ipynb', 'TP4 ML&DL.ipynb', 'TP7 DM-Copy1.ipynb', 'TP7 DM.ipynb', 'Untitled.ipynb', 'Videos', 'VirtualBox VMs', "Voisinage d'impression", 'Voisinage réseau', 'White Blue Simple Modern Enhancing Sales Strategy Presentation ....pdf']

In [4]:
import pandas as pd

print("Pandas est prêt !")

Pandas est prêt !

In [6]:
df = pd.read_excel("Online Retail.xlsx")

print("Fichier chargé avec succès !")

Fichier chargé avec succès !

In [8]:
print("Dimensions du dataset :", df.shape)

Dimensions du dataset : (541909, 8)

In [9]:
print("Noms des colonnes :")
print(df.columns.tolist())

print("\nPremières lignes :")
display(df.head())

Noms des colonnes :
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Premières lignes :

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

Le fichier `Online Retail.xlsx` a été chargé avec succès dans un DataFrame Pandas. Les huit colonnes attendues sont 
présentes : InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID et Country. Les premières lignes
montrent des informations sur les factures, les produits, les quantités, les prix, les dates et les pays.

In [11]:
print("Nombre de lignes :", df.shape[0])
print("Nombre de colonnes :", df.shape[1])

Nombre de lignes : 541909
Nombre de colonnes : 8

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [13]:
valeurs_manquantes = df.isna().sum()

print(valeurs_manquantes)

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [14]:
profil_manquants = pd.DataFrame({
    "Colonne": df.columns,
    "Valeurs_manquantes": df.isna().sum().values,
    "Pourcentage_manquant": (
        df.isna().mean().values * 100
    ).round(2)
})

display(profil_manquants)

       Colonne  Valeurs_manquantes  Pourcentage_manquant
0    InvoiceNo                   0                  0.00
1    StockCode                   0                  0.00
2  Description                1454                  0.27
3     Quantity                   0                  0.00
4  InvoiceDate                   0                  0.00
5    UnitPrice                   0                  0.00
6   CustomerID              135080                 24.93
7      Country                   0                  0.00

In [15]:
display(df.describe(include="all"))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

# Profilage et interprétation des données

In [16]:
print("Statistiques de Quantity :")
display(df["Quantity"].describe())

print("Statistiques de UnitPrice :")
display(df["UnitPrice"].describe())

print("Nombre de pays différents :",
      df["Country"].nunique())

print("Nombre de produits différents :",
      df["StockCode"].nunique())

print("Nombre de factures différentes :",
      df["InvoiceNo"].nunique())

print("Nombre de clients identifiés :",
      df["CustomerID"].nunique())

Statistiques de Quantity :

count    541909.000000
mean          9.552250
std         218.081158
min      -80995.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       80995.000000
Name: Quantity, dtype: float64

Statistiques de UnitPrice :

count    541909.000000
mean          4.611114
std          96.759853
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       38970.000000
Name: UnitPrice, dtype: float64

Nombre de pays différents : 38
Nombre de produits différents : 4070
Nombre de factures différentes : 25900
Nombre de clients identifiés : 4372

Une valeur manquante est-elle automatiquement une erreur métier?

Non, une valeur manquante n'est pas automatiquement une erreur métier. Par exemple, l'absence de CustomerID signifie que le
client n'est pas identifié dans l'enregistrement concerné. Cependant, cette absence ne prouve pas que la vente est
incorrecte. Il faut analyser le contexte et documenter cette limite avant toute décision de préparation des données.

Contrôle de traçabilité avec Python

Les statistiques descriptives montrent que la variable Quantity présente une moyenne de 9,55 et une médiane de 3, tandis que UnitPrice présente une moyenne de 4,61 et une médiane de 2,08. Les deux variables comportent des valeurs minimales négatives ainsi que des valeurs maximales élevées. Ces observations nécessitent une attention particulière lors de l'interprétation des données. À ce stade, aucune valeur n'est supprimée ou modifiée, car le TP1 porte sur le cadrage et la découverte des sources.

# Diversité des données

L'exploration de la source a permis d'identifier 38 pays distincts, 4 070 codes produit distincts, 25 900 numéros de facture distincts et 4 372 identifiants client distincts. Ces résultats montrent que la source permet d'envisager des analyses selon plusieurs axes, notamment le produit, le pays, la facture et le client. Ils constituent des indicateurs descriptifs et ne représentent pas, à eux seuls, des résultats commerciaux définitifs.

In [19]:

# Types des colonnes
print("=== TYPES DES COLONNES ===")
df.info()

# Valeurs manquantes
print("\n=== VALEURS MANQUANTES ===")
print(df.isna().sum())

# Pourcentage des valeurs manquantes
print("\n=== POURCENTAGE DES VALEURS MANQUANTES ===")
print((df.isna().mean() * 100).round(2))

=== TYPES DES COLONNES ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

=== VALEURS MANQUANTES ===
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

=== POURCENTAGE DES VALEURS MANQUANTES ===
InvoiceNo       0.00
StockCode       0.00
Description     0.27
Quantity        0.00
InvoiceDate     0.00
UnitPrice       0.00
CustomerID     24.93
Country         0.00
dtype: float64

### Analyse des valeurs manquantes

Le profilage du fichier Online Retail.xlsx révèle 1 454 valeurs manquantes dans la colonne Description, soit 0,27 % des enregistrements, et 135 080 valeurs manquantes dans la colonne CustomerID, soit 24,93 %.

Les six autres colonnes ne présentent aucune valeur manquante selon le contrôle effectué. L'absence de CustomerID limite l'identification des clients, tandis que l'absence de Description réduit la disponibilité du libellé de certains produits. Ces valeurs manquantes ne constituent pas automatiquement des erreurs métier.

À ce stade, aucune suppression ni modification n'est effectuée. Ces constats seront conservés pour l'audit et la préparation des données lors du TP2.

# Interprétation des types de données

### Analyse des types de données

L'inspection des types montre que le fichier contient quatre colonnes de type object, une colonne entière, deux colonnes de type float64 et une colonne de type datetime64[ns]. La colonne InvoiceDate permet d'identifier la date et l'heure des enregistrements. Quantity représente une quantité entière, tandis que UnitPrice contient des valeurs numériques décimales.

La colonne CustomerID est de type float64 et contient des valeurs manquantes. Ces caractéristiques sont à documenter avant toute opération de préparation des données.

Élément et Résultat observé
Source :Online Retail.xlsx

Nombre de lignes :541 909

Nombre de colonnes:8

Pays distincts:38

Codes produit distincts:4 070

Numéros de facture distincts:25 900

Identifiants client distincts:4 372

Valeurs manquantes dans Description:1 454 (0,27 %)

Valeurs manquantes dans CustomerID:135 080 (24,93 %)

Autres colonnes:Aucune valeur manquante observé

In [20]:

print("Quantités négatives :",
      (df["Quantity"] < 0).sum())

print("Prix unitaires négatifs :",
      (df["UnitPrice"] < 0).sum())

print("Date minimale :",
      df["InvoiceDate"].min())

print("Date maximale :",
      df["InvoiceDate"].max())

Quantités négatives : 10624
Prix unitaires négatifs : 2
Date minimale : 2010-12-01 08:26:00
Date maximale : 2011-12-09 12:50:00

In [17]:
questions = {
    "Evolution temporelle": [
        "InvoiceDate", "Quantity", "UnitPrice"
    ],
    "Analyse des produits": [
        "StockCode", "Description", "Quantity"
    ],
    "Analyse par pays": [
        "Country", "Quantity"
    ],
    "Commandes et clients": [
        "InvoiceNo", "CustomerID"
    ]
}

for question, champs in questions.items():
    disponibles = all(champ in df.columns for champ in champs)

    print(question, ":", "Faisable" if disponibles
          else "Champs manquants")

    print("Champs nécessaires :", champs)

Evolution temporelle : Faisable
Champs nécessaires : ['InvoiceDate', 'Quantity', 'UnitPrice']
Analyse des produits : Faisable
Champs nécessaires : ['StockCode', 'Description', 'Quantity']
Analyse par pays : Faisable
Champs nécessaires : ['Country', 'Quantity']
Commandes et clients : Faisable
Champs nécessaires : ['InvoiceNo', 'CustomerID']

In [18]:
print("Dimensions :", df.shape)

df.info()

print("\nValeurs manquantes :")
print(df.isna().sum())

print("\nStatistiques descriptives :")
display(df.describe(include="all"))

Dimensions : (541909, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

Valeurs manquantes :
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Statistiques descriptives :

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

### Résultats de l’exploration des données

L’exploration du fichier *Online Retail.xlsx* a permis d’identifier une période d’observation allant du 1er décembre 2010 à 08h26 au 9 décembre 2011 à 12h50.

Le jeu de données contient 541 909 lignes et 8 colonnes. Il comporte 38 pays distincts, 4 070 codes produits différents, 25 900 numéros de facture distincts et 4 372 clients identifiés distincts.

L’analyse des valeurs manquantes montre que la colonne `CustomerID` contient 135 080 valeurs manquantes, soit 24,93 % des lignes. La colonne `Description` contient 1 454 valeurs manquantes, soit 0,27 %. Les autres colonnes ne présentent pas de valeurs manquantes.

L’analyse descriptive révèle également 10 624 lignes avec une quantité négative et 2 lignes avec un prix unitaire négatif. Ces valeurs constituent des points d’attention qui devront être examinés lors d’une étape ultérieure d’audit et de préparation des données. À ce stade, aucune suppression ni modification n’est effectuée.

Ces résultats permettent de mieux connaître la source de données et de préparer les futures analyses décisionnelles relatives à l’évolution des ventes, aux produits, aux pays et aux clients.